language: node_js

node_js: stable  # 要安装的node版本为当前的稳定版

cache:
  directories:
  - node_modules # 要缓存的文件夹

# before_install:               # install 阶段之前执行
#   - npm install -g hexo-cli   # 全局安装 Hexo 命令行工具

install:                      # 在安装项目环境阶段需要运行的命令，一条一行，类似的还有 before_install
  - npm install               # 安装 package.json 中的依赖

script:                       # 在构建阶段需要运行的命令，一条一行，类似的还有 before_script、after_script
  - hexo generate             # Hexo 常规命令，执行清理和生成

after_success:                # script 阶段成功时执行，构建失败不会执行，其他同上
  - git config user.name "lanlan2017"
  - git config user.email "18251956727@163.com"
  - git clone -b gh-pages https://github.com/lanlan2017/test.git ./page/
  - ls
  - cp -rf ./public/ ./page/
  - cd ./page/
  - ls
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet https://github.com/lanlan2017/test.git gh-pages  # 强制覆盖gh-pages分支,HexoBlogToken是在Travis中配置环境变

# https://github.com/lanlan2017/test.git
# https://github.com/lanlan2017/test.git

branches:
only:
  - master # 触发持续集成的分支